blank_issues_enabled: false
contact_links:
  - name: ğŸ“– ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ
    url: https://kpab.github.io/pepino/
    about: ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆã®ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆã¨ã‚¬ã‚¤ãƒ‰
  - name: ğŸ’¬ è³ªå•ãƒ»ç›¸è«‡
    url: https://github.com/kpab/pepino/discussions
    about: è³ªå•ã‚„ç›¸è«‡ã¯Discussionsã§